-- AlterTable
ALTER TABLE "EventMap" ADD COLUMN     "boundsNELat" DOUBLE PRECISION,
ADD COLUMN     "boundsNELng" DOUBLE PRECISION,
ADD COLUMN     "boundsSWLat" DOUBLE PRECISION,
ADD COLUMN     "boundsSWLng" DOUBLE PRECISION;
